### ISSUE TITLE
Enable a no wifi password to be added on the wifi list

### ISSUE THREAD

**Issue by SyntaxHarvy** [SyntaxHarvy/HACWifiManager#10]
Thank you for the feature, i never thought you'll add all those options into one convenient function, I have one more concern while testing your library it doesn't accept  blank "" password, my wifi access point doesn't have password since I am using captive portal authentication, the library throws error => 2 while connecting.

_Originally posted by @rjjrbatarao in https://github.com/SyntaxHarvy/HACWifiManager/issues/7#issuecomment-986225407_

**Comment by rjjrbatarao** [comment]
Everything works smoothly now ,wifi log-in with or without password, I see that your using json on .setup as valid parameter and thats a plus (i've tested it along with this branch which works flawlessly) I will be using this library with my unfinished project( stucked with finding tidy wifi configuration ).

**Comment by SyntaxHarvy** [comment]
> Everything works smoothly now ,wifi log-in with or without password, I see that your using json on .setup as valid parameter and thats a plus (i've tested it along with this branch which works flawlessly) I will be using this library with my unfinished project( stucked with finding tidy wifi configuration ).

Great, glad that this library helps you. Cheers. 

I will merge the branch created for this issue and close this issue as well.

**Comment by SyntaxHarvy** [comment]
Closed.
