### ISSUE TITLE
Unaable to compile

### ISSUE THREAD

**Issue by mydroidbox** [SyntaxHarvy/HACWifiManager#37]
Tried to compile but no luck.
Esp32 Wrover.  ArduinoJson installed.  Arduino IDE1.8:

In file included from C:\Users\v\OneDrive\Documents\Arduino\libraries\HaCWifiManager\src/HaCWifiManager.h:79:0,
                 from C:\Users\v\AppData\Local\Temp\arduino_modified_sketch_425243\BasicWifiMngrStaAP.ino:46:
C:\Users\v\OneDrive\Documents\Arduino\libraries\HaCWifiManager\src/hacwifimanagerparameters.h:84:14: error: 'function' in namespace 'std' does not name a template type
 typedef std::function<void(const char *)> tListGenCbFnHaC1StrParamSub; // Standard void function with non-return value
              ^
C:\Users\v\OneDrive\Documents\Arduino\libraries\HaCWifiManager\src/hacwifimanagerparameters.h:85:14: error: 'function' in namespace 'std' does not name a template type
 typedef std::function<void(uint8_t)> tListGenCbFnHaC1IntParamSub;      // Standard void function with non-return value
              ^
C:\Users\v\OneDrive\Documents\Arduino\libraries\HaCWifiManager\src/hacwifimanagerparameters.h:152:18: error: 'tListGenCbFnHaC1StrParamSub' has not been declared
     void onDebug(tListGenCbFnHaC1StrParamSub fn); // Debug related events
                  ^
C:\Users\v\OneDrive\Documents\Arduino\libraries\HaCWifiManager\src/hacwifimanagerparameters.h:165:5: error: 'tListGenCbFnHaC1StrParamSub' does not name a type
     tListGenCbFnHaC1StrParamSub _onDebugFn; // Function callback declaration for debug event
     ^
C:\Users\v\OneDrive\Documents\Arduino\libraries\HaCWifiManager\src/hacwifimanagerparameters.h:169:36: error: 'tListGenCbFnHaC1IntParamSub' has not been declared
     bool _wifiExists(t_wifiInfo w, tListGenCbFnHaC1IntParamSub fn);
                                    ^
In file included from C:\Users\v\OneDrive\Documents\Arduino\libraries\HaCWifiManager\src/HaCWifiManager.h:80:0,
                 from C:\Users\v\AppData\Local\Temp\arduino_modified_sketch_425243\BasicWifiMngrStaAP.ino:46:
C:\Users\v\OneDrive\Documents\Arduino\libraries\HaCWifiManager\src/tick.h:36:14: error: 'function' in namespace 'std' does not name a template type
 typedef std::function<void()> tListGenCbFnTick;
              ^
C:\Users\v\OneDrive\Documents\Arduino\libraries\HaCWifiManager\src/tick.h:47:21: error: 'tListGenCbFnTick' has not been declared
         void onTick(tListGenCbFnTick fn);
                     ^
C:\Users\v\OneDrive\Documents\Arduino\libraries\HaCWifiManager\src/tick.h:53:9: error: 'tListGenCbFnTick' does not name a type
         tListGenCbFnTick _onTick;
         ^
In file included from C:\Users\v\AppData\Local\Temp\arduino_modified_sketch_425243\BasicWifiMngrStaAP.ino:46:0:
C:\Users\v\OneDrive\Documents\Arduino\libraries\HaCWifiManager\src/HaCWifiManager.h:183:9: error: 'WiFiSleepType' has not been declared
         WiFiSleepType wifiSleepStyle = WIFI_NONE_SLEEP,
         ^
C:\Users\v\OneDrive\Documents\Arduino\libraries\HaCWifiManager\src/HaCWifiManager.h:185:9: error: 'WiFiPhyMode' has not been declared
         WiFiPhyMode wifiPhyMode = WIFI_PHY_MODE_11G
         ^
C:\Users\v\OneDrive\Documents\Arduino\libraries\HaCWifiManager\src/HaCWifiManager.h:183:40: error: 'WIFI_NONE_SLEEP' was not declared in this scope
         WiFiSleepType wifiSleepStyle = WIFI_NONE_SLEEP,
                                        ^
C:\Users\v\OneDrive\Documents\Arduino\libraries\HaCWifiManager\src/HaCWifiManager.h:185:35: error: 'WIFI_PHY_MODE_11G' was not declared in this scope
         WiFiPhyMode wifiPhyMode = WIFI_PHY_MODE_11G
                                   ^
C:\Users\v\AppData\Local\Temp\arduino_modified_sketch_425243\BasicWifiMngrStaAP.ino: In function 'void setup()':
BasicWifiMngrStaAP:98:25: error: 'WIFI_NONE_SLEEP' was not declared in this scope
                         WIFI_NONE_SLEEP,          //Sleep style
                         ^
BasicWifiMngrStaAP:100:25: error: 'WIFI_PHY_MODE_11G' was not declared in this scope
                         WIFI_PHY_MODE_11G         //Wifi Physical mode
                         ^
Multiple libraries were found for "WiFi.h"
 Used: C:\Users\v\OneDrive\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi
 Not used: C:\Users\v\OneDrive\Documents\Arduino\libraries\WiFiEspAT
 Not used: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt\libraries\WiFi
exit status 1
'WIFI_NONE_SLEEP' was not declared in this scope

**Comment by SyntaxHarvy** [comment]
The library was not tested yet with esp32. I will take a look later.

**Comment by mydroidbox** [comment]
Thanks, appreciated.

**Comment by SyntaxHarvy** [comment]
I had updated it already, can you try this branch [https://github.com/SyntaxHarvy/HACWifiManager/tree/dev/ESP32](url) . I will merge later on once it is confirm working from your side.

**Comment by mydroidbox** [comment]
Ok now it compiles and able to login but AP page doesn't load nor automatically redirects from login.
Debug:

 Station ready. Msg => mydefaultAP 

 Station IP => => 0.0.0.0 
Error =>11
New client connected on the Access Point =>{"no_client": 1}

Also quick question. Is this where the AP name is meant to be changed I changed it but defalut ssid and password returned. hacwifimanager.h, line 159.

void setAPInfo( const char *ssid = "MyAP", 
                    const char *pass = "12345678"
                    );

**Comment by SyntaxHarvy** [comment]
> Ok now it compiles and able to login but AP page doesn't load nor automatically redirects from login. Debug:
> 
> Station ready. Msg => mydefaultAP
> 
> Station IP => => 0.0.0.0 Error =>11 New client connected on the Access Point =>{"no_client": 1}

Error 11 is due to failed to get a results on wifiscan for 3 attempt. I did increase the maximum attempt to 5 now and it should fix this issue. Kindly check again the example on same branch(dev/esp32) as i modified it a little bit on the AP steady state events which doesn't display the right IP for access point.

If you want to change the MCU AP ssid you may use this function:
void setAPInfo( const char *ssid = "mydefaultAP", 
                    const char *pass = "mydefaultAPPass"
                    );

gHaCWifiManager.setAPInfo("YourAPSSID", "YourAPPassword");

If there will be no password then set the password in to empty string.
gHaCWifiManager.setAPInfo("YourAPSSID", "");

Call this function on the setup function.
