### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by rjjrbatarao** [SyntaxHarvy/HACWifiManager#7]
Hi thank you for this wonderful library, I checked your src files maybe you could add options for these features, this keeps my wifi away from weired issues.
  WiFi.persistent(false);
  WiFi.softAPdisconnect(true);
  WiFi.setSleepMode(WIFI_NONE_SLEEP);
  WiFi.setOutputPower(16.5);
  WiFi.setPhyMode(WIFI_PHY_MODE_11G);
I was also looking for automatic fail over but i think its already handled by your multi wifi sta feature.
Regards from ArduPh member.

**Comment by SyntaxHarvy** [comment]
Created a branch for this one.

https://github.com/SyntaxHarvy/HACWifiManager/tree/dev/harvy_issues%237

You can try and check.

**Comment by rjjrbatarao** [comment]
Thank you for the feature, i never thought you'll add all those options into one convenient function, I have one more concern while testing your library it doesn't accept  blank "" password, my wifi access point doesn't have password since I am using captive portal authentication, the library throws error => 2 while connecting.

**Comment by SyntaxHarvy** [comment]
> Thank you for the feature, i never thought you'll add all those options into one convenient function, I have one more concern while testing your library it doesn't accept blank "" password, my wifi access point doesn't have password since I am using captive portal authentication, the library throws error => 2 while connecting.

I will close this current issue and open a new issue for the connection to non secured wifi or no password connection.
